defaults:
  - _self_
  - 3mlp_moving_average

seed: 42
data:
  file: "/hpc2hdd/home/mgong081/Projects/DeepSynergy/data/3mlp_data_test_fold1_tanh.p"

model:
  learning_rate: 0.0001
  dsn1_layers: [2048, 4096, 2048]
  dsn2_layers: [2048, 4096, 2048]
  cln_layers: [1024, 2048, 1024] # Example configuration for the cell line network
  spn_layers: [2048, 1024]
  best_path: # "/hpc2hdd/home/mgong081/Projects/DeepSynergy/outputs/03-27_15-15-55/best_model.pth"

training:
  batch_size: 64
  epochs: 1000
  early_stop_patience: 100

# dir
hydra:
  run:
    dir: outputs/${now:%m-%d_%H-%M-%S}
