defaults:
  - _self_

seed: 42
data:
  file: "/hpc2hdd/home/mgong081/Projects/DeepSynergy/data/3mlp_data_test_fold0_tanh.p"

model:
  dropout: 0.5
  learning_rate: 0.00001
  dsn1_layers: [2048, 4096, 2048]
  dsn2_layers: [2048, 4096, 2048]
  cln_layers: [1024, 2048, 1024] # Example configuration for the cell line network
  spn_layers: [2048, 1024]
  log_dir:

training:
  batch_size: 64
  epochs: 2
  early_stop_patience: 1

# dir
hydra:
  run:
    dir: outputs/${now:%m-%d_%H-%M-%S}
